workspace:
  base: /go
  path: src/github.com/uswitch/oauth2_proxy

pipeline:
  build:
    image: golang:1.9
    commands:
      - go get -v -t ./...
      - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o bin/proxy

  publish:
    when:
      event: push
      branch: master
    image: plugins/docker
    registry: quay.io
    repo: quay.io/uswitch/oauth2_proxy
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_COMMIT_SHA}
      - ${DRONE_COMMIT_BRANCH}
      - latest
      - stable
